### PR TITLE
Support for BouncyCastle BKS and UBER keystores

### PR DESCRIPTION
**Pull request by voetsjoeba**
In this PR:
 - Support for BouncyCastle keystore formats: BKS, BKS-V1 and UBER
 - Added \_\_version__ attribute to the jks package

### CODE REVIEW

**Comment by mahmoud** [comment]
This is looking REAL good. Though I see some tabs that should probably be spaces. I can fix them after merge, if you'd prefer.

**Comment by voetsjoeba** [comment]
Oh yeah feel free, must have had my editor settings wrong at the time.

**Comment by voetsjoeba** [comment]
Oh I see, I put `noet` instead of `et` in my modline on tools/readks.py. I'll take care of that and retab real quick.

**Comment by mahmoud** [comment]
Reviewed this with Kurt. It looks pretty good! I may go in and edit/reformat a few docstrings for readability, but without question the greatest PR I've ever merged (with all due respect to my other collaborators).

**Comment by mahmoud** [comment]
(Also, it rolled us over to the 100th commit, hooray!) :tada: :balloon: :tada:

**Pull request merged**
